package mustafaozhan.github.com.mycurrencies.extensions

import android.arch.lifecycle.LifecycleOwner
import android.arch.lifecycle.LiveData
import android.arch.lifecycle.Observer
import com.crashlytics.android.Crashlytics
import mustafaozhan.github.com.mycurrencies.main.fragment.model.CurrencyResponse
import mustafaozhan.github.com.mycurrencies.main.fragment.model.Rates
import mustafaozhan.github.com.mycurrencies.room.dao.CurrencyDao
import mustafaozhan.github.com.mycurrencies.room.model.Currency
import mustafaozhan.github.com.mycurrencies.room.model.OfflineRates

/**
 * Created by Mustafa Ozhan on 2018-07-20.
 */
fun <T> LiveData<T>.reObserve(owner: LifecycleOwner, observer: Observer<T>) {
    removeObserver(observer)
    observe(owner, observer)
}

fun calculateResultByCurrency(name: String, value: String, rate: Rates?): Double {
    return try {
        rate?.getThroughReflection<Double>(name)?.times(value.toDouble()) ?: 0.0
    } catch (e: NumberFormatException) {
        e.printStackTrace()
        Crashlytics.logException(e)
        0.0
    }
}

fun CurrencyDao.insertInitialCurrencies() {
    apply {
        insertCurrency(Currency("AED"))
        insertCurrency(Currency("AFN"))
        insertCurrency(Currency("ALL"))
        insertCurrency(Currency("AMD"))
        insertCurrency(Currency("ANG"))
        insertCurrency(Currency("AOA"))
        insertCurrency(Currency("ARS"))
        insertCurrency(Currency("AUD"))
        insertCurrency(Currency("AWG"))
        insertCurrency(Currency("AZN"))
        insertCurrency(Currency("BAM"))
        insertCurrency(Currency("BBD"))
        insertCurrency(Currency("BDT"))
        insertCurrency(Currency("BGN"))
        insertCurrency(Currency("BHD"))
        insertCurrency(Currency("BIF"))
        insertCurrency(Currency("BMD"))
        insertCurrency(Currency("BND"))
        insertCurrency(Currency("BOB"))
        insertCurrency(Currency("BRL"))
        insertCurrency(Currency("BSD"))
        insertCurrency(Currency("BTC"))
        insertCurrency(Currency("BTN"))
        insertCurrency(Currency("BWP"))
        insertCurrency(Currency("BYN"))
        insertCurrency(Currency("BYR"))
        insertCurrency(Currency("BZD"))
        insertCurrency(Currency("CAD"))
        insertCurrency(Currency("CDF"))
        insertCurrency(Currency("CHF"))
        insertCurrency(Currency("CLF"))
        insertCurrency(Currency("CLP"))
        insertCurrency(Currency("CNY"))
        insertCurrency(Currency("COP"))
        insertCurrency(Currency("CRC"))
        insertCurrency(Currency("CUC"))
        insertCurrency(Currency("CUP"))
        insertCurrency(Currency("CVE"))
        insertCurrency(Currency("CZK"))
        insertCurrency(Currency("DJF"))
        insertCurrency(Currency("DKK"))
        insertCurrency(Currency("DOP"))
        insertCurrency(Currency("DZD"))
        insertCurrency(Currency("EGP"))
        insertCurrency(Currency("ERN"))
        insertCurrency(Currency("ETB"))
        insertCurrency(Currency("EUR"))
        insertCurrency(Currency("FJD"))
        insertCurrency(Currency("FKP"))
        insertCurrency(Currency("GBP"))
        insertCurrency(Currency("GEL"))
        insertCurrency(Currency("GGP"))
        insertCurrency(Currency("GHS"))
        insertCurrency(Currency("GIP"))
        insertCurrency(Currency("GMD"))
        insertCurrency(Currency("GNF"))
        insertCurrency(Currency("GTQ"))
        insertCurrency(Currency("GYD"))
        insertCurrency(Currency("HKD"))
        insertCurrency(Currency("HNL"))
        insertCurrency(Currency("HRK"))
        insertCurrency(Currency("HTG"))
        insertCurrency(Currency("HUF"))
        insertCurrency(Currency("IDR"))
        insertCurrency(Currency("ILS"))
        insertCurrency(Currency("IMP"))
        insertCurrency(Currency("INR"))
        insertCurrency(Currency("IQD"))
        insertCurrency(Currency("IRR"))
        insertCurrency(Currency("ISK"))
        insertCurrency(Currency("JEP"))
        insertCurrency(Currency("JMD"))
        insertCurrency(Currency("JOD"))
        insertCurrency(Currency("JPY"))
        insertCurrency(Currency("KES"))
        insertCurrency(Currency("KGS"))
        insertCurrency(Currency("KHR"))
        insertCurrency(Currency("KMF"))
        insertCurrency(Currency("KPW"))
        insertCurrency(Currency("KRW"))
        insertCurrency(Currency("KWD"))
        insertCurrency(Currency("KYD"))
        insertCurrency(Currency("KZT"))
        insertCurrency(Currency("LAK"))
        insertCurrency(Currency("LBP"))
        insertCurrency(Currency("LKR"))
        insertCurrency(Currency("LRD"))
        insertCurrency(Currency("LSL"))
        insertCurrency(Currency("LTL"))
        insertCurrency(Currency("LVL"))
        insertCurrency(Currency("LYD"))
        insertCurrency(Currency("MAD"))
        insertCurrency(Currency("MDL"))
        insertCurrency(Currency("MGA"))
        insertCurrency(Currency("MKD"))
        insertCurrency(Currency("MMK"))
        insertCurrency(Currency("MNT"))
        insertCurrency(Currency("MOP"))
        insertCurrency(Currency("MRO"))
        insertCurrency(Currency("MUR"))
        insertCurrency(Currency("MVR"))
        insertCurrency(Currency("MWK"))
        insertCurrency(Currency("MXN"))
        insertCurrency(Currency("MYR"))
        insertCurrency(Currency("MZN"))
        insertCurrency(Currency("NAD"))
        insertCurrency(Currency("NGN"))
        insertCurrency(Currency("NIO"))
        insertCurrency(Currency("NOK"))
        insertCurrency(Currency("NPR"))
        insertCurrency(Currency("NZD"))
        insertCurrency(Currency("OMR"))
        insertCurrency(Currency("PAB"))
        insertCurrency(Currency("PEN"))
        insertCurrency(Currency("PGK"))
        insertCurrency(Currency("PHP"))
        insertCurrency(Currency("PKR"))
        insertCurrency(Currency("PLN"))
        insertCurrency(Currency("PYG"))
        insertCurrency(Currency("QAR"))
        insertCurrency(Currency("RON"))
        insertCurrency(Currency("RSD"))
        insertCurrency(Currency("RUB"))
        insertCurrency(Currency("RWF"))
        insertCurrency(Currency("SAR"))
        insertCurrency(Currency("SBD"))
        insertCurrency(Currency("SCR"))
        insertCurrency(Currency("SDG"))
        insertCurrency(Currency("SEK"))
        insertCurrency(Currency("SGD"))
        insertCurrency(Currency("SHP"))
        insertCurrency(Currency("SLL"))
        insertCurrency(Currency("SOS"))
        insertCurrency(Currency("SRD"))
        insertCurrency(Currency("STD"))
        insertCurrency(Currency("SVC"))
        insertCurrency(Currency("SYP"))
        insertCurrency(Currency("SZL"))
        insertCurrency(Currency("THB"))
        insertCurrency(Currency("TJS"))
        insertCurrency(Currency("TMT"))
        insertCurrency(Currency("TND"))
        insertCurrency(Currency("TOP"))
        insertCurrency(Currency("TRY"))
        insertCurrency(Currency("TTD"))
        insertCurrency(Currency("TWD"))
        insertCurrency(Currency("TZS"))
        insertCurrency(Currency("UAH"))
        insertCurrency(Currency("UGX"))
        insertCurrency(Currency("USD"))
        insertCurrency(Currency("UYU"))
        insertCurrency(Currency("UZS"))
        insertCurrency(Currency("VEF"))
        insertCurrency(Currency("VND"))
        insertCurrency(Currency("VUV"))
        insertCurrency(Currency("WST"))
        insertCurrency(Currency("XAF"))
        insertCurrency(Currency("XAG"))
        insertCurrency(Currency("XAU"))
        insertCurrency(Currency("XCD"))
        insertCurrency(Currency("XDR"))
        insertCurrency(Currency("XOF"))
        insertCurrency(Currency("XPF"))
        insertCurrency(Currency("YER"))
        insertCurrency(Currency("ZAR"))
        insertCurrency(Currency("ZMK"))
        insertCurrency(Currency("ZMW"))
        insertCurrency(Currency("ZWL"))
    }
}

fun CurrencyResponse.toOfflineRates() = OfflineRates(rates?.findBase().toString(),
    rates?.AED,
    rates?.AFN,
    rates?.ALL,
    rates?.AMD,
    rates?.ANG,
    rates?.AOA,
    rates?.ARS,
    rates?.AUD,
    rates?.AWG,
    rates?.AZN,
    rates?.BAM,
    rates?.BBD,
    rates?.BDT,
    rates?.BGN,
    rates?.BHD,
    rates?.BIF,
    rates?.BMD,
    rates?.BND,
    rates?.BOB,
    rates?.BRL,
    rates?.BSD,
    rates?.BTC,
    rates?.BTN,
    rates?.BWP,
    rates?.BYN,
    rates?.BYR,
    rates?.BZD,
    rates?.CAD,
    rates?.CDF,
    rates?.CHF,
    rates?.CLF,
    rates?.CLP,
    rates?.CNY,
    rates?.COP,
    rates?.CRC,
    rates?.CUC,
    rates?.CUP,
    rates?.CVE,
    rates?.CZK,
    rates?.DJF,
    rates?.DKK,
    rates?.DOP,
    rates?.DZD,
    rates?.EGP,
    rates?.ERN,
    rates?.ETB,
    rates?.EUR,
    rates?.FJD,
    rates?.FKP,
    rates?.GBP,
    rates?.GEL,
    rates?.GGP,
    rates?.GHS,
    rates?.GIP,
    rates?.GMD,
    rates?.GNF,
    rates?.GTQ,
    rates?.GYD,
    rates?.HKD,
    rates?.HNL,
    rates?.HRK,
    rates?.HTG,
    rates?.HUF,
    rates?.IDR,
    rates?.ILS,
    rates?.IMP,
    rates?.INR,
    rates?.IQD,
    rates?.IRR,
    rates?.ISK,
    rates?.JEP,
    rates?.JMD,
    rates?.JOD,
    rates?.JPY,
    rates?.KES,
    rates?.KGS,
    rates?.KHR,
    rates?.KMF,
    rates?.KPW,
    rates?.KRW,
    rates?.KWD,
    rates?.KYD,
    rates?.KZT,
    rates?.LAK,
    rates?.LBP,
    rates?.LKR,
    rates?.LRD,
    rates?.LSL,
    rates?.LTL,
    rates?.LVL,
    rates?.LYD,
    rates?.MAD,
    rates?.MDL,
    rates?.MGA,
    rates?.MKD,
    rates?.MMK,
    rates?.MNT,
    rates?.MOP,
    rates?.MRO,
    rates?.MUR,
    rates?.MVR,
    rates?.MWK,
    rates?.MXN,
    rates?.MYR,
    rates?.MZN,
    rates?.NAD,
    rates?.NGN,
    rates?.NIO,
    rates?.NOK,
    rates?.NPR,
    rates?.NZD,
    rates?.OMR,
    rates?.PAB,
    rates?.PEN,
    rates?.PGK,
    rates?.PHP,
    rates?.PKR,
    rates?.PLN,
    rates?.PYG,
    rates?.QAR,
    rates?.RON,
    rates?.RSD,
    rates?.RUB,
    rates?.RWF,
    rates?.SAR,
    rates?.SBD,
    rates?.SCR,
    rates?.SDG,
    rates?.SEK,
    rates?.SGD,
    rates?.SHP,
    rates?.SLL,
    rates?.SOS,
    rates?.SRD,
    rates?.STD,
    rates?.SVC,
    rates?.SYP,
    rates?.SZL,
    rates?.THB,
    rates?.TJS,
    rates?.TMT,
    rates?.TND,
    rates?.TOP,
    rates?.TRY,
    rates?.TTD,
    rates?.TWD,
    rates?.TZS,
    rates?.UAH,
    rates?.UGX,
    rates?.USD,
    rates?.UYU,
    rates?.UZS,
    rates?.VEF,
    rates?.VND,
    rates?.VUV,
    rates?.WST,
    rates?.XAF,
    rates?.XAG,
    rates?.XAU,
    rates?.XCD,
    rates?.XDR,
    rates?.XOF,
    rates?.XPF,
    rates?.YER,
    rates?.ZAR,
    rates?.ZMK,
    rates?.ZMW,
    rates?.ZWL

)

fun OfflineRates.getRates(): Rates? = Rates(
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTC,
    BTN,
    BWP,
    BYN,
    BYR,
    BZD,
    CAD,
    CDF,
    CHF,
    CLF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GGP,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    IMP,
    INR,
    IQD,
    IRR,
    ISK,
    JEP,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LTL,
    LVL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRO,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLL,
    SOS,
    SRD,
    STD,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    UYU,
    UZS,
    VEF,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XCD,
    XDR,
    XOF,
    XPF,
    YER,
    ZAR,
    ZMK,
    ZMW,
    ZWL
)

fun Rates.findBase() =
    this::class.java.fields.firstOrNull {
        this.getThroughReflection<Double>(it.name) == 1.0
    }?.name ?: "NULL"

inline fun <reified T : Any> Any.getThroughReflection(propertyName: String): T? {
    val getterName = "get" + propertyName.capitalize()
    return try {
        javaClass.getMethod(getterName).invoke(this) as? T
    } catch (e: NoSuchMethodException) {
        null
    }
}