package mustafaozhan.github.com.mycurrencies.extensions

import android.arch.persistence.db.SupportSQLiteDatabase

/**
 * Created by Mustafa Ozhan on 2018-10-28.
 */
@Suppress("LongMethod")
fun SupportSQLiteDatabase.execSQL1To2() {
    execSQL("ALTER TABLE offline_rates ADD COLUMN AED REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AFN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ALLL REAL DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AMD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ANG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AOA REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ARS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AWG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AZN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BAM REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BBD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BDT REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BHD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BIF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BMD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BND REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BOB REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BSD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BTC REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BTN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BWP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BYN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BYR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BZD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CDF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CLF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CLP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN COP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CRC REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CUC REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CUP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CVE REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN DJF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN DOP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN DZD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN EGP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ERN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ETB REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN FJD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN FKP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GEL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GGP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GHS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GIP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GMD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GNF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GTQ REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GYD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN HNL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN HTG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN IMP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN IQD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN IRR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ISK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN JEP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN JMD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN JOD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KES REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KGS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KHR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KMF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KPW REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KWD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KYD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KZT REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LAK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LBP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LKR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LRD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LSL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LTL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LVL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LYD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MAD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MDL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MGA REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MKD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MMK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MNT REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MOP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MRO REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MUR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MVR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MWK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MZN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN NAD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN NGN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN NIO REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN NPR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN OMR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PAB REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PEN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PGK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PKR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PYG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN QAR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN RSD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN RWF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SAR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SBD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SCR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SDG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SHP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SLL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SOS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SRD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN STD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SVC REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SYP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SZL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TJS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TMT REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TND REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TOP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TTD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TWD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TZS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN UAH REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN UGX REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN UYU REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN UZS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN VEF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN VND REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN VUV REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN WST REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XAF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XAG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XAU REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XCD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XDR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XOF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XPF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN YER REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ZMK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ZMW REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ZWL REAL  DEFAULT 0.0")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AED',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AFN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ALL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AMD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ANG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AOA',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ARS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AWG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AZN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BAM',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BBD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BDT',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BHD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BIF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BMD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BND',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BOB',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BSD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BTC',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BTN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BWP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BYN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BYR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BZD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CDF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CLF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CLP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('COP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CRC',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CUC',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CUP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CVE',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('DJF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('DOP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('DZD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('EGP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ERN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ETB',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('FJD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('FKP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GEL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GGP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GHS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GIP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GMD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GNF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GTQ',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GYD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('HNL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('HTG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('IMP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('IQD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('IRR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ISK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('JEP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('JMD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('JOD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KES',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KGS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KHR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KMF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KPW',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KWD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KYD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KZT',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LAK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LBP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LKR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LRD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LSL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LTL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LVL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LYD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MAD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MDL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MGA',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MKD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MMK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MNT',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MOP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MRO',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MUR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MVR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MWK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MZN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('NAD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('NGN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('NIO',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('NPR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('OMR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PAB',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PEN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PGK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PKR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PYG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('QAR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('RSD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('RWF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SAR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SBD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SCR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SDG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SHP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SLL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SOS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SRD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('STD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SVC',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SYP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SZL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TJS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TMT',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TND',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TOP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TTD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TWD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TZS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('UAH',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('UGX',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('UYU',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('UZS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('VEF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('VND',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('VUV',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('WST',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XAF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XAG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XAU',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XCD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XDR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XOF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XPF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('YER',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ZMK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ZMW',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ZWL',0.0,1)")
}
