package mustafaozhan.github.com.mycurrencies.extensions

import android.arch.persistence.db.SupportSQLiteDatabase

/**
 * Created by Mustafa Ozhan on 2018-10-28.
 */
@Suppress("LongMethod")
fun SupportSQLiteDatabase.execSQL1To2() {
    execSQL("ALTER TABLE offline_rates ADD COLUMN AED REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AFN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ALLL REAL DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AMD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ANG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AOA REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ARS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AWG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN AZN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BAM REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BBD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BDT REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BHD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BIF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BMD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BND REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BOB REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BSD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BTC REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BTN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BWP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BYN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BYR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN BZD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CDF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CLF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CLP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN COP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CRC REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CUC REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CUP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN CVE REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN DJF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN DOP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN DZD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN EGP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ERN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ETB REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN FJD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN FKP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GEL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GGP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GHS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GIP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GMD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GNF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GTQ REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN GYD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN HNL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN HTG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN IMP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN IQD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN IRR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ISK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN JEP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN JMD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN JOD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KES REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KGS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KHR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KMF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KPW REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KWD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KYD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN KZT REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LAK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LBP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LKR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LRD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LSL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LTL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LVL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN LYD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MAD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MDL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MGA REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MKD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MMK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MNT REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MOP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MRO REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MUR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MVR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MWK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN MZN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN NAD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN NGN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN NIO REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN NPR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN OMR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PAB REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PEN REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PGK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PKR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN PYG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN QAR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN RSD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN RWF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SAR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SBD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SCR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SDG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SHP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SLL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SOS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SRD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN STD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SVC REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SYP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN SZL REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TJS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TMT REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TND REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TOP REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TTD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TWD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN TZS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN UAH REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN UGX REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN UYU REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN UZS REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN VEF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN VND REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN VUV REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN WST REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XAF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XAG REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XAU REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XCD REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XDR REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XOF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN XPF REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN YER REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ZMK REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ZMW REAL  DEFAULT 0.0")
    execSQL("ALTER TABLE offline_rates ADD COLUMN ZWL REAL  DEFAULT 0.0")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AED',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AFN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ALL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AMD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ANG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AOA',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ARS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AWG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('AZN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BAM',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BBD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BDT',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BHD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BIF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BMD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BND',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BOB',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BSD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BTC',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BTN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BWP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BYN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BYR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('BZD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CDF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CLF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CLP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('COP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CRC',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CUC',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CUP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('CVE',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('DJF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('DOP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('DZD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('EGP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ERN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ETB',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('FJD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('FKP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GEL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GGP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GHS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GIP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GMD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GNF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GTQ',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('GYD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('HNL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('HTG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('IMP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('IQD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('IRR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ISK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('JEP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('JMD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('JOD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KES',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KGS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KHR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KMF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KPW',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KWD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KYD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('KZT',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LAK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LBP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LKR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LRD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LSL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LTL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LVL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('LYD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MAD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MDL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MGA',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MKD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MMK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MNT',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MOP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MRO',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MUR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MVR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MWK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('MZN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('NAD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('NGN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('NIO',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('NPR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('OMR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PAB',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PEN',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PGK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PKR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('PYG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('QAR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('RSD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('RWF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SAR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SBD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SCR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SDG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SHP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SLL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SOS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SRD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('STD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SVC',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SYP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('SZL',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TJS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TMT',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TND',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TOP',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TTD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TWD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('TZS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('UAH',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('UGX',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('UYU',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('UZS',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('VEF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('VND',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('VUV',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('WST',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XAF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XAG',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XAU',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XCD',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XDR',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XOF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('XPF',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('YER',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ZMK',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ZMW',0.0,1)")
    execSQL("INSERT INTO currency (name,rate,isActive) VALUES ('ZWL',0.0,1)")
}

@Suppress("LongMethod", "MaximumLineLength")
fun SupportSQLiteDatabase.execSQL2To3() {
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('AED',0.0,1,'United Arab Emirates dirham','\u062f.\u0625')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('AFN',0.0,1,'Afghan afghani','\u060b')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ALL',0.0,1,'Albanian lek','Lek')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('AMD',0.0,1,'Armenian dram','\u058f')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ANG',0.0,1,'Netherlands Antillean guilder','\u0192')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('AOA',0.0,1,'Angolan kwanza','Kz')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ARS',0.0,1,'Argentine peso','N$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('AWG',0.0,1,'Australian dollar','AU$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('AZN',0.0,1,'Aruban florin','\u0192')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BAM',0.0,1,'Azerbaijani manat','\u20bc')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BBD',0.0,1,'Bosnia and Herzegovina convertible mark','KM')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BDT',0.0,1,'Barbadian dollar','Bds$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BHD',0.0,1,'Bangladeshi taka','\u09f3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BIF',0.0,1,'Bulgarian lev','\u043b\u0432')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BMD',0.0,1,'Bahraini dinar','\u062f.\u0628')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BND',0.0,1,'Burundian franc','Fr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BOB',0.0,1,'Bermudian dollar','BD$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BSD',0.0,1,'Brunei dollar','B$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BTC',0.0,1,'Bolivian boliviano','\$b')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BTN',0.0,1,'Brazilian real','R$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BWP',0.0,1,'Bahamian dollar','B$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BYN',0.0,1,'Bhutanese ngultrum','Nu.')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BYR',0.0,1,'Botswana pula','P')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('BZD',0.0,1,'Belarusian ruble','Br')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('CDF',0.0,1,'Belarusian ruble','Br')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('CLF',0.0,1,'Belize dollar','BZ$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('CLP',0.0,1,'Canadian dollar','C$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('COP',0.0,1,'Congolese franc','Fr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('CRC',0.0,1,'Swiss franc','CHF')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('CUC',0.0,1,'Chilean Unit of Account','UF')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('CUP',0.0,1,'Chilean peso','CLP$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('CVE',0.0,1,'Chinese yuan','\u5143')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('DJF',0.0,1,'Colombian peso','COL$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('DOP',0.0,1,'Costa Rican col\u00f3n','\u20a1')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('DZD',0.0,1,'Bitcoin','\u0e3f')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('EGP',0.0,1,'Cuban convertible peso','CUC$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ERN',0.0,1,'Cuban peso','\$MN')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ETB',0.0,1,'Cape Verdean escudo','Esc')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('FJD',0.0,1,'Czech koruna','K\u010d')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('FKP',0.0,1,'Djiboutian franc','Fr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('GEL',0.0,1,'Danish krone','kr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('GGP',0.0,1,'Dominican peso','RD$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('GHS',0.0,1,'Algerian dinar','\u062f.\u062c')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('GIP',0.0,1,'Egyptian pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('GMD',0.0,1,'Eritrean nakfa','Nfk')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('GNF',0.0,1,'Ethiopian birr','Br')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('GTQ',0.0,1,'Euro','\u20ac')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('GYD',0.0,1,'Fijian dollar','FJ$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('HNL',0.0,1,'Falkland Islands pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('HTG',0.0,1,'British pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('IMP',0.0,1,'Georgian lari','\u20be')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('IQD',0.0,1,'Guernsey pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('IRR',0.0,1,'Ghanaian cedi','\u20b5')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ISK',0.0,1,'Gibraltar pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('JEP',0.0,1,'Gambian dalasi','D')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('JMD',0.0,1,'Guinean franc','Fr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('JOD',0.0,1,'Guatemalan quetzal','Q')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('KES',0.0,1,'Guyanese dollar','GY$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('KGS',0.0,1,'Hong Kong dollar','HK$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('KHR',0.0,1,'Honduran lempira','L')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('KMF',0.0,1,'Croatian kuna','kn')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('KPW',0.0,1,'Haitian gourde','G')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('KWD',0.0,1,'Hungarian forint','Ft')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('KYD',0.0,1,'Indonesian rupiah','Rp')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('KZT',0.0,1,'Israeli new shekel','\u20aa')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('LAK',0.0,1,'Manx pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('LBP',0.0,1,'Indian rupee','\u20b9')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('LKR',0.0,1,'Iraqi dinar','\u0639.\u062f')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('LRD',0.0,1,'Iranian rial','\ufdfc')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('LSL',0.0,1,'Icelandic kr\u00f3na','kr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('LTL',0.0,1,'Jersey pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('LVL',0.0,1,'Jamaican dollar','J$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('LYD',0.0,1,'Jordanian dinar','\u062f.\u0627')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MAD',0.0,1,'Japanese yen','\u00a5')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MDL',0.0,1,'Kenyan shilling','Sh')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MGA',0.0,1,'Kyrgyzstani som','\u0441')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MKD',0.0,1,'Cambodian riel','\u17db')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MMK',0.0,1,'Comorian franc','Fr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MNT',0.0,1,'North Korean won','\u20a9')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MOP',0.0,1,'South Korean won','\u20a9')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MRO',0.0,1,'Kuwaiti dinar','\u062f.\u0643')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MUR',0.0,1,'Cayman Islands dollar','CI$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MVR',0.0,1,'Kazakhstani tenge','\u20b8')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MWK',0.0,1,'Lao kip','\u20ad')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('MZN',0.0,1,'Lebanese pound','\u0644.\u0644')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('NAD',0.0,1,'Sri Lankan rupee','Rs')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('NGN',0.0,1,'Liberian dollar','LD$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('NIO',0.0,1,'Lesotho loti','L')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('NPR',0.0,1,'Lithuania Litas','Lt')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('OMR',0.0,1,'Latvia Lat','\u200eLs')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('PAB',0.0,1,'Libyan dinar','\u0644.\u062f')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('PEN',0.0,1,'Moroccan dirham','\u062f.\u0645.')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('PGK',0.0,1,'Moldovan leu','L')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('PKR',0.0,1,'Malagasy ariary','Ar')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('PYG',0.0,1,'Macedonian denar','\u0434\u0435\u043d')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('QAR',0.0,1,'Burmese kyat','Ks')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('RSD',0.0,1,'Mongolian t\u00f6gr\u00f6g','\u20ae')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('RWF',0.0,1,'Macanese pataca','P')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SAR',0.0,1,'Mauritanian ouguiya','UM')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SBD',0.0,1,'Mauritian rupee','\u20a8')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SCR',0.0,1,'Maldivian rufiyaa','.\u0783')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SDG',0.0,1,'Malawian kwacha','MK')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SHP',0.0,1,'Mexican peso','Mex$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SLL',0.0,1,'Malaysian ringgit','RM')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SOS',0.0,1,'Mozambican metical','MT')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SRD',0.0,1,'Namibian dollar','N$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('STD',0.0,1,'Nigerian naira','\u20a6')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SVC',0.0,1,'Nicaraguan c\u00f3rdoba','C')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SYP',0.0,1,'Norwegian krone','kr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('SZL',0.0,1,'Nepalese rupee','\u20a8')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('TJS',0.0,1,'New Zealand dollar','NZ$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('TMT',0.0,1,'Omani rial','\ufdfc')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('TND',0.0,1,'Panamanian balboa','B\\/.')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('TOP',0.0,1,'Peruvian sol','S\\/.')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('TTD',0.0,1,'Papua New Guinean kina','K')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('TWD',0.0,1,'Philippine piso','\u20b1')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('TZS',0.0,1,'Pakistani rupee','\u20a8')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('UAH',0.0,1,'Polish z\u0142oty','z\u0142')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('UGX',0.0,1,'Paraguayan guaran\u00ed','\u20b2')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('UYU',0.0,1,'Qatari riyal','\ufdfc')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('UZS',0.0,1,'Romanian leu','lei')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('VEF',0.0,1,'Serbian dinar','\u0434\u0438\u043d.')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('VND',0.0,1,'Russian ruble','\u20bd')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('VUV',0.0,1,'Rwandan franc','Fr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('WST',0.0,1,'Saudi riyal','\u0631.\u0633')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('XAF',0.0,1,'Solomon Islands dollar','SI$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('XAG',0.0,1,'Seychellois rupee','\u20a8')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('XAU',0.0,1,'Sudanese pound','\u202b\u062c.\u0633.\u202c')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('XCD',0.0,1,'Swedish krona','kr')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('XDR',0.0,1,'Singapore dollar','S$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('XOF',0.0,1,'Saint Helena pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('XPF',0.0,1,'Sierra Leonean leone','Le')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('YER',0.0,1,'Somali shilling','Sh')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ZMK',0.0,1,'Surinamese dollar','Sr$')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ZMW',0.0,1,'South Sudanese pound','\u00a3')")
    execSQL("INSERT INTO currency (name,rate,isActive,description) VALUES ('ZWL',0.0,1,'S\u00e3o Tom\u00e9 and Pr\u00edncipe dobra','Db')")
}
