coverage:
  precision: 2
  round: nearest
  range: "0..100"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        informational: true
comment: # this is a top-level key
  layout: "diff, reach, files"
