package mustafaozhan.github.com.mycurrencies.room

import android.arch.persistence.db.SupportSQLiteDatabase
import android.arch.persistence.room.Database
import android.arch.persistence.room.Room
import android.arch.persistence.room.RoomDatabase
import android.arch.persistence.room.migration.Migration
import mustafaozhan.github.com.mycurrencies.application.Application
import mustafaozhan.github.com.mycurrencies.room.dao.CurrencyDao
import mustafaozhan.github.com.mycurrencies.room.dao.OfflineRatesDao
import mustafaozhan.github.com.mycurrencies.room.model.Currency
import mustafaozhan.github.com.mycurrencies.room.model.OfflineRates

/**
 * Created by Mustafa Ozhan on 2018-07-16.
 */
@Database(entities = [(Currency::class), (OfflineRates::class)], version = 2, exportSchema = false)
abstract class AppDatabase : RoomDatabase() {

    companion object {
        private val FROM_1_TO_2 = object : Migration(1, 2) {
            override fun migrate(database: SupportSQLiteDatabase) {
                database.apply {
                    execSQL("ALTER TABLE offline_rates ADD COLUMN AED REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN AFN REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ALLL REAL DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN AMD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ANG REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN AOA REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ARS REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN AWG REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN AZN REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BAM REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BBD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BDT REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BHD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BIF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BMD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BND REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BOB REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BSD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BTC REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BTN REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BWP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BYN REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BYR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN BZD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN CDF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN CLF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN CLP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN COP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN CRC REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN CUC REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN CUP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN CVE REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN DJF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN DOP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN DZD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN EGP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ERN REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ETB REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN FJD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN FKP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN GEL REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN GGP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN GHS REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN GIP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN GMD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN GNF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN GTQ REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN GYD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN HNL REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN HTG REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN IMP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN IQD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN IRR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ISK REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN JEP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN JMD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN JOD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN KES REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN KGS REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN KHR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN KMF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN KPW REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN KWD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN KYD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN KZT REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN LAK REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN LBP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN LKR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN LRD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN LSL REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN LTL REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN LVL REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN LYD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MAD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MDL REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MGA REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MKD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MMK REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MNT REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MOP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MRO REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MUR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MVR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MWK REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN MZN REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN NAD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN NGN REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN NIO REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN NPR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN OMR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN PAB REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN PEN REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN PGK REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN PKR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN PYG REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN QAR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN RSD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN RWF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SAR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SBD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SCR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SDG REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SHP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SLL REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SOS REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SRD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN STD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SVC REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SYP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN SZL REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN TJS REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN TMT REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN TND REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN TOP REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN TTD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN TWD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN TZS REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN UAH REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN UGX REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN UYU REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN UZS REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN VEF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN VND REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN VUV REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN WST REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN XAF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN XAG REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN XAU REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN XCD REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN XDR REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN XOF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN XPF REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN YER REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ZMK REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ZMW REAL  DEFAULT 0.0")
                    execSQL("ALTER TABLE offline_rates ADD COLUMN ZWL REAL  DEFAULT 0.0")
                }
            }
        }
        val database = Room.databaseBuilder(Application.instance.applicationContext, AppDatabase::class.java, "app_db")
                .addMigrations(FROM_1_TO_2).allowMainThreadQueries().build()
    }

    abstract fun currencyDao(): CurrencyDao

    abstract fun offlineRatesDao(): OfflineRatesDao

}