source "https://rubygems.org"

gem "fastlane", "2.211.0"
gem "cocoapods", "1.11.3"
gem "xcode-install", "2.8.1"
gem "fastlane-plugin-firebase_app_distribution", "0.3.7"

eval_gemfile("fastlane/Pluginfile")
