name: Add Android inputs

inputs:
  SECRET_PASSWORD:
    required: true
  ANDROID_GPG_RELEASE_KEYSTORE:
    required: true
  RELEASE_GOOGLE_SERVICES_JSON_ASC:
    required: true
  DEBUG_GOOGLE_SERVICES_JSON_ASC:
    required: true
  AG_CONNECT_SERVICES_JSON_ASC:
    required: true

runs:
  using: "composite"
  steps:
    - name: Adding secret files
      run: |
        echo "${{ inputs.ANDROID_GPG_RELEASE_KEYSTORE }}" > release.keystore.asc
        gpg -d --passphrase "${{ inputs.SECRET_PASSWORD }}" --batch release.keystore.asc > android/release.keystore
        mkdir android/src/release
        echo "${{ inputs.RELEASE_GOOGLE_SERVICES_JSON_ASC }}" > google-services.json.asc
        gpg -d --passphrase "${{ inputs.SECRET_PASSWORD }}" --batch google-services.json.asc > android/src/release/google-services.json
        mkdir android/src/debug
        echo "${{ inputs.DEBUG_GOOGLE_SERVICES_JSON_ASC }}" > google-services.json.asc
        gpg -d --passphrase "${{ inputs.SECRET_PASSWORD }}" --batch google-services.json.asc > android/src/debug/google-services.json
        echo "${{ inputs.AG_CONNECT_SERVICES_JSON_ASC }}" > agconnect-services.json.asc
        gpg -d --passphrase "${{ inputs.SECRET_PASSWORD }}" --batch agconnect-services.json.asc > android/src/release/agconnect-services.json
