/*
 * Copyright (c) 2021 Mustafa Ozhan. All rights reserved.
 */

@Suppress("SpellCheckingInspection")
object Versions {
    const val KOTLIN = "1.6.10"
    const val ANDROID_GRADLE_PLUGIN = "7.1.2"
    const val ANDROID_MATERIAL = "1.4.0"
    const val CONSTRAINT_LAYOUT = "2.1.3"
    const val KTOR = "1.6.7"
    const val LOG_BACK = "1.2.10"
    const val KOIN = "3.1.5"
    const val KERMIT = "1.0.3"
    const val MULTIPLATFORM_SETTINGS = "0.8.1"
    const val FIREBASE_ANALYTICS = "20.1.0"
    const val FIREBASE_CRASHLYTICS = "18.2.8"
    const val FIREBASE_REMOTE_CONFIG = "21.0.1"
    const val DESUGARING = "1.1.5"
    const val ANR_WATCH_DOG = "1.4.0"
    const val GSM = "4.3.10"
    const val CRASHLYTICS = "2.8.1"
    const val ADMOB = "20.6.0"
    const val NAVIGATION = "2.3.5"
    const val PLAY_CORE = "1.10.3"
    const val KOTLIN_X_DATE_TIME = "0.3.2"
    const val COROUTINES = "1.5.2-native-mt"
    const val BILLING = "4.1.0"
    const val LEAK_CANARY = "2.8.1"
    const val SQL_DELIGHT = "1.5.3"
    const val LIFECYCLE = "2.4.1"
    const val MOKO_RESOURCES = "0.18.0"
    const val DEPENDENCY_UPDATES = "0.42.0"
    const val BUILD_HEALTH = "0.80.0"
    const val BUILD_KONFIG = "0.11.0"
    const val WORK_RUNTIME = "2.7.1"
    const val SPLASH_SCREEN = "1.0.0-alpha02"
    const val KOVER = "0.5.0"
    const val HUAWEI_HSM_BASE = "6.4.0.300"
    const val ROOT_BEER = "0.1.0"
    const val MOCKATIVE = "1.1.4"
    const val KSP = "1.6.10-1.0.4"
}
