/*
 * Copyright (c) 2021 Mustafa Ozhan. All rights reserved.
 */

@Suppress("SpellCheckingInspection")
object Versions {
    const val KOTLIN = "1.7.21"
    const val KSP = "$KOTLIN-1.0.8"
    const val ANDROID_GRADLE_PLUGIN = "7.3.1"
    const val ANDROID_MATERIAL = "1.7.0"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val KTOR = "2.1.3"
    const val LOG_BACK = "1.4.5"
    const val KOIN = "3.2.2"
    const val KOIN_ANDROID = "3.3.0"
    const val MULTIPLATFORM_SETTINGS = "0.9"
    const val FIREBASE_ANALYTICS = "21.2.0"
    const val FIREBASE_REMOTE_CONFIG = "21.2.0"
    const val DESUGARING = "1.2.2"
    const val GSM = "4.3.14"
    const val FIREBASE_PER = "20.3.0"
    const val FIREBASE_PER_PLUGIN = "1.4.2"
    const val CRASHLYTICS = "2.9.2"
    const val ADMOB = "21.3.0"
    const val NAVIGATION = "2.5.3"
    const val PLAY_CORE = "1.10.3"
    const val KOTLIN_X_DATE_TIME = "0.4.0"
    const val COROUTINES = "1.6.4"
    const val BILLING = "5.1.0"
    const val LEAK_CANARY = "2.10"
    const val SQL_DELIGHT = "1.5.4"
    const val LIFECYCLE = "2.5.1"
    const val MOKO_RESOURCES = "0.20.1"
    const val DEPENDENCY_UPDATES = "0.44.0"
    const val BUILD_KONFIG = "0.13.3"
    const val WORK_RUNTIME = "2.7.1"
    const val SPLASH_SCREEN = "1.0.0"
    const val KOVER = "0.6.1"
    const val ROOT_BEER = "0.1.0"
    const val MOCKATIVE = "1.2.6"
    const val FIREBASE_CRASHLYTICS = "18.3.2"
    const val ANR_WATCH_DOG = "1.4.0"
    const val KERMIT = "1.1.3"
}
