/*
 * Copyright (c) 2021 Mustafa Ozhan. All rights reserved.
 */

@Suppress("SpellCheckingInspection")
object Versions {
    const val KOTLIN = "1.6.21"
    const val KSP = "$KOTLIN-1.0.5"
    const val ANDROID_GRADLE_PLUGIN = "7.2.1"
    const val ANDROID_MATERIAL = "1.6.1"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val KTOR = "1.6.8"
    const val LOG_BACK = "1.2.11"
    const val KOIN = "3.1.6"
    const val MULTIPLATFORM_SETTINGS = "0.9"
    const val FIREBASE_ANALYTICS = "21.0.0"
    const val FIREBASE_REMOTE_CONFIG = "21.1.0"
    const val DESUGARING = "1.1.5"
    const val GSM = "4.3.10"
    const val CRASHLYTICS = "2.9.0"
    const val ADMOB = "21.0.0"
    const val NAVIGATION = "2.3.5"
    const val PLAY_CORE = "1.10.3"
    const val KOTLIN_X_DATE_TIME = "0.3.2"
    const val COROUTINES = "1.5.2-native-mt"
    const val BILLING = "4.1.0"
    const val LEAK_CANARY = "2.9.1"
    const val SQL_DELIGHT = "1.5.3"
    const val LIFECYCLE = "2.4.1"
    const val MOKO_RESOURCES = "0.20.1"
    const val DEPENDENCY_UPDATES = "0.42.0"
    const val BUILD_HEALTH = "1.5.0"
    const val BUILD_KONFIG = "0.12.0"
    const val WORK_RUNTIME = "2.7.1"
    const val SPLASH_SCREEN = "1.0.0-alpha02"
    const val KOVER = "0.5.1"
    const val ROOT_BEER = "0.1.0"
    const val MOCKATIVE = "1.2.5"
    const val SCOPE_MOB = "2.1.5"
    const val PARSER_MOB = "1.1.6"
    const val BASE_MOB = "2.1.4"
    const val LOG_MOB = "2.2.1"
}
