package config.key

enum class FlavoredKey(
    val googleDefault: String,
    val huaweiDefault: String
) {
    BANNER_AD_UNIT_ID_CALCULATOR_RELEASE(Fakes.Google.BANNER_AD_UNIT_ID, Fakes.Huawei.BANNER_AD_UNIT_ID),
    BANNER_AD_UNIT_ID_SETTINGS_RELEASE(Fakes.Google.BANNER_AD_UNIT_ID, Fakes.Huawei.BANNER_AD_UNIT_ID),
    BANNER_AD_UNIT_ID_CURRENCIES_RELEASE(Fakes.Google.BANNER_AD_UNIT_ID, Fakes.Huawei.BANNER_AD_UNIT_ID),
    INTERSTITIAL_AD_ID_RELEASE(Fakes.Google.INTERSTITIAL_AD_ID, Fakes.Huawei.INTERSTITIAL_AD_ID),
    REWARDED_AD_UNIT_ID_RELEASE(Fakes.Google.REWARDED_AD_UNIT_ID, Fakes.Huawei.REWARDED_AD_UNIT_ID),

    BANNER_AD_UNIT_ID_CALCULATOR_DEBUG(Fakes.Google.BANNER_AD_UNIT_ID, Fakes.Huawei.BANNER_AD_UNIT_ID),
    BANNER_AD_UNIT_ID_SETTINGS_DEBUG(Fakes.Google.BANNER_AD_UNIT_ID, Fakes.Huawei.BANNER_AD_UNIT_ID),
    BANNER_AD_UNIT_ID_CURRENCIES_DEBUG(Fakes.Google.BANNER_AD_UNIT_ID, Fakes.Huawei.BANNER_AD_UNIT_ID),
    INTERSTITIAL_AD_ID_DEBUG(Fakes.Google.INTERSTITIAL_AD_ID, Fakes.Huawei.INTERSTITIAL_AD_ID),
    REWARDED_AD_UNIT_ID_DEBUG(Fakes.Google.REWARDED_AD_UNIT_ID, Fakes.Huawei.REWARDED_AD_UNIT_ID);
}
