name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/reusable-project.yml@6c7b329cd65b22c4cbdf59dda5f9436e54f1c26f
    with:
      project_id: 13
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
