name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/reusable-project.yml@d2d760603ad21c392c22ab10508941b6f65a3cf1
    with:
      project_id: 13
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
