name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/reusable-project.yml@17e6f5436e23d9f5ded36c820801cdac40fd99cf
    with:
      project_id: 13
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
